"""Provider-neutral Ambient Life Context contracts (synthetic/manual in Stage 6)."""

from companion.life_context.models import (
    ContextSourceHealth,
    LifeContextObservation,
    SignalFreshness,
    classify_observation_eligibility,
)
from companion.life_context.stage12 import (
    CalendarAvailabilityWindow,
    CalendarBusyInterval,
    CalendarContextActivationBundle,
    CalendarImportPolicy,
    ConsentScopeRevision,
    ContextIngestResult,
    ContextObservationDraft,
    ContextSourceHealthDraft,
    ContextSourceCapability,
    ContextSourceDescriptor,
    ContextSourceHealthV2,
    ContextSourceStateRevision,
    ContextCapabilityStateRevision,
    ContextCollectionPermit,
    ContextCollectionPermitRequest,
    ContextRetentionExpiryIntent,
    ContextRetentionExpiryReceipt,
    ContextRestoreQuarantine,
    ContextSourceErasureTombstone,
    WindowsContextActivationBundle,
    DeviceActivitySummary,
    LifeContextObservationV2,
    RetentionPolicy,
    SamplingPolicy,
    sign_observation_draft,
    sign_health_draft,
    sign_collection_permit_request,
    verify_collection_permit_request_signature,
    verify_health_draft_signature,
    verify_observation_draft_signature,
    classify_external_observation_eligibility,
)

__all__ = [
    "ContextSourceHealth", "LifeContextObservation", "SignalFreshness",
    "classify_observation_eligibility",
    "CalendarAvailabilityWindow",
    "CalendarBusyInterval",
    "CalendarContextActivationBundle",
    "CalendarImportPolicy",
    "ConsentScopeRevision",
    "ContextIngestResult",
    "ContextObservationDraft",
    "ContextSourceHealthDraft",
    "ContextSourceCapability",
    "ContextSourceDescriptor",
    "ContextSourceHealthV2",
    "ContextSourceStateRevision",
    "ContextCapabilityStateRevision",
    "ContextCollectionPermit",
    "ContextCollectionPermitRequest",
    "ContextRetentionExpiryIntent",
    "ContextRetentionExpiryReceipt",
    "ContextRestoreQuarantine",
    "ContextSourceErasureTombstone",
    "WindowsContextActivationBundle",
    "DeviceActivitySummary",
    "LifeContextObservationV2",
    "RetentionPolicy",
    "SamplingPolicy",
    "sign_observation_draft",
    "sign_health_draft",
    "sign_collection_permit_request",
    "verify_collection_permit_request_signature",
    "verify_health_draft_signature",
    "verify_observation_draft_signature",
    "classify_external_observation_eligibility",
]
